### ISSUE TITLE
Scalability and maintainability

### ISSUE THREAD

**Issue by songyanho** [opensistemas-hub/osbrain#310] opened 2018-08-17 18:06 UTC
I have recently built a MAS with osBrain but the main concern is it comes with one nameserver in which it is not fault tolerant. May I know how to solve this issue or is there any better deployment strategy to handle more than 1000 agents registered in one name server?

**Comment by Peque** [comment] 2018-08-19 12:11
@songyanho There is currently no other way to handle that. Pyro4 may have something already implemented. If that is the case, we could integrate it in osBrain. Otherwise I do not think we will implement that in the short term. Feel free to contribute code if you want! :blush:

I think this is a duplicate of: https://github.com/opensistemas-hub/osbrain/issues/310

Feel free to reopen if it is not.

Thanks for reporting this issue!

**Closed by Peque** 2018-08-19 12:11 UTC
Labels: question

**Comment by Peque** [comment] 2018-08-19 12:13
@songyanho PS: do not forget to react with :+1: in #310 so that we know there are more people interested on that issue. :wink:

**Comment by Peque** [comment] 2018-08-30 07:10
@songyanho Sorry, I meant #115, not #310. :sweat_smile:
